//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_GROUP
    {
        public ACCOUNT_GROUP()
        {
            this.ACCOUNT = new HashSet<ACCOUNT>();
            this.DEALER_GROUP = new HashSet<DEALER_GROUP>();
            this.LOT_BY_GROUP = new HashSet<LOT_BY_GROUP>();
            this.MARKUP_BY_GROUP = new HashSet<MARKUP_BY_GROUP>();
            this.CHANNEL = new HashSet<CHANNEL>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public bool IsReal { get; set; }
        public Nullable<int> DefaultVirtualDepo { get; set; }
        public decimal BrokerLeverage { get; set; }
        public decimal MarginCallPercentLevel { get; set; }
        public decimal StopoutPercentLevel { get; set; }
        public int MarkupType { get; set; }
        public double DefaultMarkupPoints { get; set; }
        public bool SwapFree { get; set; }
    
        public virtual ICollection<ACCOUNT> ACCOUNT { get; set; }
        public virtual ICollection<DEALER_GROUP> DEALER_GROUP { get; set; }
        public virtual ICollection<LOT_BY_GROUP> LOT_BY_GROUP { get; set; }
        public virtual ICollection<MARKUP_BY_GROUP> MARKUP_BY_GROUP { get; set; }
        public virtual ICollection<CHANNEL> CHANNEL { get; set; }
    }
}
