//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class BALANCE_CHANGE
    {
        public BALANCE_CHANGE()
        {
            this.TRANSFER = new HashSet<TRANSFER>();
        }
    
        public int ID { get; set; }
        public int AccountID { get; set; }
        public int ChangeType { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime ValueDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> Position { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ICollection<TRANSFER> TRANSFER { get; set; }
    }
}
