//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class BROKER_ORDER
    {
        public int ID { get; set; }
        public string Ticker { get; set; }
        public int Instrument { get; set; }
        public int Volume { get; set; }
        public int Side { get; set; }
        public int OrderPricing { get; set; }
        public Nullable<decimal> RequestedPrice { get; set; }
        public Nullable<decimal> Slippage { get; set; }
        public string Dealer { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> ClosingPositionID { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public int RequestID { get; set; }
        public string Comment { get; set; }
        public string ExpertComment { get; set; }
        public Nullable<int> Magic { get; set; }
        public double Markup { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual DEALER DEALER1 { get; set; }
        public virtual SPOT SPOT { get; set; }
    }
}
