//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANNEL
    {
        public CHANNEL()
        {
            this.ACCOUNT_GROUP = new HashSet<ACCOUNT_GROUP>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Cachable { get; set; }
    
        public virtual ICollection<ACCOUNT_GROUP> ACCOUNT_GROUP { get; set; }
    }
}
