//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMODITY
    {
        public COMMODITY()
        {
            this.ACCOUNT = new HashSet<ACCOUNT>();
            this.PAYMENT_SYSTEM_TRANSFER = new HashSet<PAYMENT_SYSTEM_TRANSFER>();
            this.SERVICE = new HashSet<SERVICE>();
            this.WALLET = new HashSet<WALLET>();
        }
    
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> CodeFXI { get; set; }
        public Nullable<decimal> InterestRatePercent { get; set; }
        public int ComType { get; set; }
    
        public virtual ICollection<ACCOUNT> ACCOUNT { get; set; }
        public virtual ICollection<PAYMENT_SYSTEM_TRANSFER> PAYMENT_SYSTEM_TRANSFER { get; set; }
        public virtual ICollection<SERVICE> SERVICE { get; set; }
        public virtual ICollection<WALLET> WALLET { get; set; }
    }
}
