//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEALER_GROUP
    {
        public string Dealer { get; set; }
        public string AccountGroup { get; set; }
        public string SessionName { get; set; }
        public string MessageQueue { get; set; }
        public string HedgingAccount { get; set; }
        public string SenderCompId { get; set; }
    
        public virtual ACCOUNT_GROUP ACCOUNT_GROUP { get; set; }
        public virtual DEALER DEALER1 { get; set; }
    }
}
