//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEALER
    {
        public DEALER()
        {
            this.BROKER_ORDER = new HashSet<BROKER_ORDER>();
            this.DEALER_GROUP = new HashSet<DEALER_GROUP>();
            this.DEALER_PARAMETER = new HashSet<DEALER_PARAMETER>();
        }
    
        public string Code { get; set; }
        public string FileName { get; set; }
        public bool DealerEnabled { get; set; }
    
        public virtual ICollection<BROKER_ORDER> BROKER_ORDER { get; set; }
        public virtual ICollection<DEALER_GROUP> DEALER_GROUP { get; set; }
        public virtual ICollection<DEALER_PARAMETER> DEALER_PARAMETER { get; set; }
    }
}
