//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENGINE_METADATA
    {
        public int ID { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public string ParamType { get; set; }
        public string Value { get; set; }
    }
}
