//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_BILL
    {
        public int Position { get; set; }
        public int MarkupType { get; set; }
        public double MarkupEnter { get; set; }
        public double MarkupExit { get; set; }
        public double MarkupBroker { get; set; }
        public double ProfitBroker { get; set; }
    }
}
