//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_SYSTEM_TRANSFER
    {
        public int Id { get; set; }
        public Nullable<int> UserPaymentSys { get; set; }
        public decimal Ammount { get; set; }
        public string Currency { get; set; }
        public System.DateTime DateProcessed { get; set; }
        public System.DateTime DateValue { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Transfer { get; set; }
        public string SourcePaySysAccount { get; set; }
        public string SourcePaySysPurse { get; set; }
        public string SourseFirstName { get; set; }
        public string SourseLastName { get; set; }
        public string SourseEmail { get; set; }
    
        public virtual COMMODITY COMMODITY { get; set; }
        public virtual TRANSFER TRANSFER1 { get; set; }
        public virtual USER_PAYMENT_SYSTEM USER_PAYMENT_SYSTEM { get; set; }
    }
}
