//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class PENDING_ORDER_CLOSED
    {
        public PENDING_ORDER_CLOSED()
        {
            this.POSITION2 = new HashSet<POSITION>();
        }
    
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int Status { get; set; }
        public System.DateTime TimeClosed { get; set; }
        public decimal PriceClosed { get; set; }
        public string CloseReason { get; set; }
        public int AccountID { get; set; }
        public string Symbol { get; set; }
        public int Volume { get; set; }
        public decimal PriceFrom { get; set; }
        public Nullable<decimal> PriceTo { get; set; }
        public Nullable<System.DateTime> TimeFrom { get; set; }
        public Nullable<System.DateTime> TimeTo { get; set; }
        public int Side { get; set; }
        public string Comment { get; set; }
        public string ExpertComment { get; set; }
        public Nullable<int> Magic { get; set; }
        public Nullable<decimal> Stoploss { get; set; }
        public Nullable<decimal> Takeprofit { get; set; }
        public Nullable<int> PairOCO { get; set; }
        public Nullable<int> Position { get; set; }
        public int PriceSide { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual POSITION POSITION1 { get; set; }
        public virtual SPOT SPOT { get; set; }
        public virtual ICollection<POSITION> POSITION2 { get; set; }
    }
}
