//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class PENDING_ORDER
    {
        public PENDING_ORDER()
        {
            this.POSITION_CLOSED = new HashSet<POSITION_CLOSED>();
        }
    
        public int ID { get; set; }
        public int AccountID { get; set; }
        public string Symbol { get; set; }
        public int Volume { get; set; }
        public decimal PriceFrom { get; set; }
        public Nullable<decimal> PriceTo { get; set; }
        public Nullable<System.DateTime> TimeFrom { get; set; }
        public Nullable<System.DateTime> TimeTo { get; set; }
        public int Side { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Magic { get; set; }
        public Nullable<decimal> Stoploss { get; set; }
        public Nullable<decimal> Takeprofit { get; set; }
        public Nullable<int> PairOCO { get; set; }
        public string ExpertComment { get; set; }
        public int PriceSide { get; set; }
        public Nullable<decimal> TrailLevel1 { get; set; }
        public Nullable<decimal> TrailTarget1 { get; set; }
        public Nullable<decimal> TrailLevel2 { get; set; }
        public Nullable<decimal> TrailTarget2 { get; set; }
        public Nullable<decimal> TrailLevel3 { get; set; }
        public Nullable<decimal> TrailTarget3 { get; set; }
        public Nullable<decimal> TrailLevel4 { get; set; }
        public Nullable<decimal> TrailTarget4 { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual SPOT SPOT { get; set; }
        public virtual ICollection<POSITION_CLOSED> POSITION_CLOSED { get; set; }
    }
}
