//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLATFORM_USER_ACCOUNT
    {
        public int PlatformUser { get; set; }
        public int Account { get; set; }
        public int RightsMask { get; set; }
    
        public virtual ACCOUNT ACCOUNT1 { get; set; }
        public virtual PLATFORM_USER PLATFORM_USER { get; set; }
    }
}
