//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION
    {
        public POSITION()
        {
            this.PENDING_ORDER_CLOSED = new HashSet<PENDING_ORDER_CLOSED>();
        }
    
        public int ID { get; set; }
        public int State { get; set; }
        public string Symbol { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> PendingOrderID { get; set; }
        public int Volume { get; set; }
        public string Comment { get; set; }
        public string ExpertComment { get; set; }
        public Nullable<int> Magic { get; set; }
        public decimal PriceEnter { get; set; }
        public System.DateTime TimeEnter { get; set; }
        public int Side { get; set; }
        public Nullable<decimal> Stoploss { get; set; }
        public Nullable<decimal> Takeprofit { get; set; }
        public Nullable<decimal> PriceBest { get; set; }
        public Nullable<decimal> PriceWorst { get; set; }
        public Nullable<decimal> TrailLevel1 { get; set; }
        public Nullable<decimal> TrailTarget1 { get; set; }
        public Nullable<decimal> TrailLevel2 { get; set; }
        public Nullable<decimal> TrailTarget2 { get; set; }
        public Nullable<decimal> TrailLevel3 { get; set; }
        public Nullable<decimal> TrailTarget3 { get; set; }
        public Nullable<decimal> TrailLevel4 { get; set; }
        public Nullable<decimal> TrailTarget4 { get; set; }
        public Nullable<int> MasterOrder { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ICollection<PENDING_ORDER_CLOSED> PENDING_ORDER_CLOSED { get; set; }
        public virtual PENDING_ORDER_CLOSED PENDING_ORDER_CLOSED1 { get; set; }
        public virtual SPOT SPOT { get; set; }
    }
}
