//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION_MARKUP
    {
        public int ID { get; set; }
        public decimal MarkupEnter { get; set; }
        public decimal MarkupExit { get; set; }
        public decimal MarkupBroker { get; set; }
        public decimal ProfitBroker { get; set; }
        public int HedgingRule { get; set; }
    }
}
