//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION_CLOSED
    {
        public int ID { get; set; }
        public string Symbol { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> PendingOrderID { get; set; }
        public int Volume { get; set; }
        public string Comment { get; set; }
        public string ExpertComment { get; set; }
        public Nullable<int> Magic { get; set; }
        public decimal PriceEnter { get; set; }
        public decimal PriceExit { get; set; }
        public System.DateTime TimeEnter { get; set; }
        public System.DateTime TimeExit { get; set; }
        public int Side { get; set; }
        public Nullable<decimal> Stoploss { get; set; }
        public Nullable<decimal> Takeprofit { get; set; }
        public Nullable<decimal> PriceBest { get; set; }
        public Nullable<decimal> PriceWorst { get; set; }
        public int ExitReason { get; set; }
        public decimal Swap { get; set; }
        public decimal ResultPoints { get; set; }
        public decimal ResultBase { get; set; }
        public decimal ResultDepo { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual PENDING_ORDER PENDING_ORDER { get; set; }
        public virtual SPOT SPOT { get; set; }
    }
}
