//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_RATE
    {
        public int Service { get; set; }
        public int RateType { get; set; }
        public decimal UserBalance { get; set; }
        public decimal Amount { get; set; }
    
        public virtual SERVICE SERVICE1 { get; set; }
    }
}
