//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE
    {
        public SERVICE()
        {
            this.SERVICE_RATE = new HashSet<SERVICE_RATE>();
            this.SUBSCRIPTION = new HashSet<SUBSCRIPTION>();
        }
    
        public int ID { get; set; }
        public int User { get; set; }
        public decimal FixedPrice { get; set; }
        public string Comment { get; set; }
        public short ServiceType { get; set; }
        public string Currency { get; set; }
        public Nullable<int> AccountId { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual COMMODITY COMMODITY { get; set; }
        public virtual PLATFORM_USER PLATFORM_USER { get; set; }
        public virtual ICollection<SERVICE_RATE> SERVICE_RATE { get; set; }
        public virtual ICollection<SUBSCRIPTION> SUBSCRIPTION { get; set; }
    }
}
