//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPOT
    {
        public SPOT()
        {
            this.BROKER_ORDER = new HashSet<BROKER_ORDER>();
            this.LOT_BY_GROUP = new HashSet<LOT_BY_GROUP>();
            this.MARKUP_BY_GROUP = new HashSet<MARKUP_BY_GROUP>();
            this.PENDING_ORDER = new HashSet<PENDING_ORDER>();
            this.PENDING_ORDER_CLOSED = new HashSet<PENDING_ORDER_CLOSED>();
            this.POSITION = new HashSet<POSITION>();
            this.POSITION_CLOSED = new HashSet<POSITION_CLOSED>();
        }
    
        public string ComBase { get; set; }
        public string ComCounter { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> SwapBuy { get; set; }
        public Nullable<decimal> SwapSell { get; set; }
        public Nullable<int> MinVolume { get; set; }
        public Nullable<int> MinStepVolume { get; set; }
        public string Description { get; set; }
        public int Precise { get; set; }
        public Nullable<int> CodeFXI { get; set; }
    
        public virtual ICollection<BROKER_ORDER> BROKER_ORDER { get; set; }
        public virtual ICollection<LOT_BY_GROUP> LOT_BY_GROUP { get; set; }
        public virtual ICollection<MARKUP_BY_GROUP> MARKUP_BY_GROUP { get; set; }
        public virtual ICollection<PENDING_ORDER> PENDING_ORDER { get; set; }
        public virtual ICollection<PENDING_ORDER_CLOSED> PENDING_ORDER_CLOSED { get; set; }
        public virtual ICollection<POSITION> POSITION { get; set; }
        public virtual ICollection<POSITION_CLOSED> POSITION_CLOSED { get; set; }
    }
}
