//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIPTION
    {
        public int Service { get; set; }
        public int User { get; set; }
        public System.DateTime TimeStarted { get; set; }
        public System.DateTime TimeEnd { get; set; }
        public bool RenewAuto { get; set; }
    
        public virtual PLATFORM_USER PLATFORM_USER { get; set; }
        public virtual SERVICE SERVICE1 { get; set; }
        public virtual SUBSCRIPTION_SIGNAL SUBSCRIPTION_SIGNAL { get; set; }
    }
}
