//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIPTION_V
    {
        public int Service { get; set; }
        public int User { get; set; }
        public System.DateTime TimeStarted { get; set; }
        public System.DateTime TimeEnd { get; set; }
        public Nullable<bool> RenewAuto { get; set; }
        public Nullable<bool> ShouldReceiveEmail { get; set; }
        public Nullable<bool> AutoTrade { get; set; }
        public Nullable<double> MaxLeverage { get; set; }
        public Nullable<double> PercentLeverage { get; set; }
        public Nullable<bool> HedgingOrdersEnabled { get; set; }
        public Nullable<int> FixedVolume { get; set; }
        public Nullable<int> MinVolume { get; set; }
        public Nullable<int> MaxVolume { get; set; }
        public Nullable<int> VolumeRound { get; set; }
        public Nullable<int> StepVolume { get; set; }
        public Nullable<decimal> FixedPrice { get; set; }
        public string Comment { get; set; }
        public short ServiceType { get; set; }
        public string Currency { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> TargetAccount { get; set; }
    }
}
