//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOP_PORTFOLIO
    {
        public TOP_PORTFOLIO()
        {
            this.USER_TOP_PORTFOLIO = new HashSet<USER_TOP_PORTFOLIO>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Criteria { get; set; }
        public int ParticipantCount { get; set; }
        public bool DescendingOrder { get; set; }
        public Nullable<double> MarginValue { get; set; }
        public Nullable<int> ManagedAccount { get; set; }
        public Nullable<int> OwnerUser { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual PLATFORM_USER PLATFORM_USER { get; set; }
        public virtual ICollection<USER_TOP_PORTFOLIO> USER_TOP_PORTFOLIO { get; set; }
    }
}
