//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSFER
    {
        public TRANSFER()
        {
            this.PAYMENT_SYSTEM_TRANSFER = new HashSet<PAYMENT_SYSTEM_TRANSFER>();
        }
    
        public int ID { get; set; }
        public int User { get; set; }
        public Nullable<int> RefWallet { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime ValueDate { get; set; }
        public decimal TargetAmount { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Subscription { get; set; }
        public Nullable<int> BalanceChange { get; set; }
    
        public virtual BALANCE_CHANGE BALANCE_CHANGE { get; set; }
        public virtual ICollection<PAYMENT_SYSTEM_TRANSFER> PAYMENT_SYSTEM_TRANSFER { get; set; }
        public virtual PLATFORM_USER PLATFORM_USER { get; set; }
    }
}
