//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_INFO
    {
        public int Id { get; set; }
        public string AvatarBig { get; set; }
        public string AvatarSmall { get; set; }
        public string About { get; set; }
        public string Contacts { get; set; }
    
        public virtual FILE FILE_ABOUT { get; set; }
        public virtual FILE FILE_BIG { get; set; }
        public virtual FILE FILE_SMALL { get; set; }
        public virtual PLATFORM_USER PLATFORM_USER { get; set; }
    }
}
