//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_EVENT
    {
        public int User { get; set; }
        public System.DateTime Time { get; set; }
        public short Code { get; set; }
        public short Action { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public Nullable<int> Account { get; set; }
    
        public virtual ACCOUNT ACCOUNT1 { get; set; }
        public virtual PLATFORM_USER PLATFORM_USER { get; set; }
    }
}
