//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PAYMENT_SYSTEM
    {
        public USER_PAYMENT_SYSTEM()
        {
            this.PAYMENT_SYSTEM_TRANSFER = new HashSet<PAYMENT_SYSTEM_TRANSFER>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public byte SystemPayment { get; set; }
        public string RootId { get; set; }
        public string PurseId { get; set; }
        public bool PurseConfirm { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<PAYMENT_SYSTEM_TRANSFER> PAYMENT_SYSTEM_TRANSFER { get; set; }
        public virtual PLATFORM_USER PLATFORM_USER { get; set; }
    }
}
