//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class WALLET
    {
        public int User { get; set; }
        public string Currency { get; set; }
        public decimal Balance { get; set; }
        public string Password { get; set; }
    
        public virtual COMMODITY COMMODITY { get; set; }
        public virtual PLATFORM_USER PLATFORM_USER { get; set; }
    }
}
