//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Chat.Server.BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.DateTime SendTimeStamp { get; set; }
        public int Sender { get; set; }
        public string RoomName { get; set; }
        public string Text { get; set; }
        public Nullable<int> Receiver { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
