//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Chat.Server.BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLATFORM_USER
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronym { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int RoleMask { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    }
}
