//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Chat.Server.BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomRole
    {
        public int User { get; set; }
        public string Room { get; set; }
        public int Role { get; set; }
    }
}
