//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Chat.Server.BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Message = new HashSet<Message>();
        }
    
        public string Name { get; set; }
        public int Owner { get; set; }
        public string Description { get; set; }
        public string Greeting { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> ExpireTimeStamp { get; set; }
        public bool IsBound { get; set; }
    
        public virtual ICollection<Message> Message { get; set; }
    }
}
