<html>
<head>
   <title>Registration form</title>
   <link href="wr_styles.css" rel="stylesheet" type="text/css">
</head>
<div align="center">
<form method="POST">
   <table>
   <tr><td align="right">Name:</td>            <td><input type="text"     name="user[name]"             value="<?=$this->user[name]?>"  size="30" /></td></tr>
   <tr><td align="right">E-mail</td>           <td><input type="text"     name="user[email]"            value="<?=$this->user[email]?>" size="30"  /></td></tr>
   <tr><td align="right">Group:</td>           <td><select                name="user[group]"            value="<?=$this->user[group]?>" style="width: 173px;">
      <option>demoforex</option>
      <option>demoforex-usd</option>
      <option>demoforex-eur</option>
      <option>demoforex-jpy</option>
   </select></tr>
   <tr><td align="right">Leverage:</td>        <td><select                name="user[leverage]"         value="<?=$this->user[leverage]?>">
      <option>50</option>
      <option>100</option>
      <option>200</option>
      <option>400</option>
   </select></tr>
   <tr><td align="right">Deposit (for demo only):</td>         <td><select                name="user[deposit]"          value="<?=$this->user[deposit]?>">
      <option>0</option>
      <option>1000</option>
      <option>5000</option>
      <option>10000</option>
   </select></tr>
   <tr><td align="right">Password:</td>        <td><input type="password" name="user[password]"         value="<?=$this->user[password]?>"         size="30"  /></td></tr>
   <tr><td align="right">Confirm password:</td><td><input type="password" name="user[confirm_password]" value="<?=$this->user[confirm_password]?>" size="30" /></td></tr>
   <tr><td align="right">City:</td>            <td><input type="text"     name="user[city]"             value="<?=$this->user[city]?>"             size="30" /></td></tr>
   <tr><td align="right">Zip:</td>             <td><input type="text"     name="user[zipcode]"          value="<?=$this->user[zipcode]?>"          size="30"  /></td></tr>
   <tr><td align="right">State:</td>           <td><input type="text"     name="user[state]"            value="<?=$this->user[state]?>"            size="30" /></td></tr>
   <tr><td align="right">Country:</td>         <td><select                name="user[country]"          value="<?=$this->user[country]?>"          style="width: 173px;">
      <option>Afganistan</option>
      <option>Albania</option>
      <option>Algeria</option>
      <option>American Samoa</option>
      <option>Andorra</option>
      <option>Angola</option>
      <option>Anguilla</option>
      <option>Antigua & Barbuda</option>
      <option>Argentina</option>
      <option>Armenia</option>
      <option>Aruba</option>
      <option>Australia</option>
      <option>Austria</option>
      <option>Azerbaijan</option>
      <option>Azores</option>
      <option>Bahamas</option>
      <option>Bahrain</option>
      <option>Bangladesh</option>
      <option>Barbados</option>
      <option>Belarus</option>
      <option>Belgium</option>
      <option>Benin</option>
      <option>Bermuda</option>
      <option>Bhutan</option>
      <option>Bolivia</option>
      <option>Bonaire</option>
      <option>Bosnia & Herzegovina</option>
      <option>Botswana</option>
      <option>Brazil</option>
      <option>British Indian Ocean Ter</option>
      <option>Brunei</option>
      <option>Bulgaria</option>
      <option>Burkina Faso</option>
      <option>Burundi</option>
      <option>Cambodia</option>
      <option>Cameroon</option>
      <option>Canada</option>
      <option>Canary Islands</option>
      <option>Cape Verde</option>
      <option>Cayman Islands</option>
      <option>Central African Republic</option>
      <option>Chad</option>
      <option>Channel Islands</option>
      <option>Chile</option>
      <option>China</option>
      <option>Christmas Island</option>
      <option>Cocos Island</option>
      <option>Columbia</option>
      <option>Comoros</option>
      <option>Congo</option>
      <option>Cook Islands</option>
      <option>Costa Rica</option>
      <option>Cote D'ivoire</option>
      <option>Croatia</option>
      <option>Cuba</option>
      <option>Curaco</option>
      <option>Cyprus</option>
      <option>Czeck Republic</option>
      <option>Denmark</option>
      <option>Djibouti</option>
      <option>Dominica</option>
      <option>Dominican Republic</option>
      <option>Dubai</option>
      <option>East Timor</option>
      <option>Ecuador</option>
      <option>Egypt</option>
      <option>El Salvador</option>
      <option>Equatorial Guinea</option>
      <option>Eritrea</option>
      <option>Estonia</option>
      <option>Ethiopia</option>
      <option>Falkland Islands</option>
      <option>Faroe Islands</option>
      <option>Fiji</option>
      <option>Finland</option>
      <option>France</option>
      <option>French Guiana</option>
      <option>French Polynesia</option>
      <option>French Southern Ter</option>
      <option>Gabon</option>
      <option>Gambia</option>
      <option>Georgia</option>
      <option>Germany</option>
      <option>Ghana</option>
      <option>Gibraltar</option>
      <option>Great Britain</option>
      <option>Greece</option>
      <option>Greenland</option>
      <option>Grenada</option>
      <option>Guadeloupe</option>
      <option>Guam</option>
      <option>Guatemala</option>
      <option>Guinea</option>
      <option>Guyana</option>
      <option>Haiti</option>
      <option>Hawaii</option>
      <option>Honduras</option>
      <option>Hong Kong</option>
      <option>Hungary</option>
      <option>Iceland</option>
      <option>India</option>
      <option>Indonesia</option>
      <option>Iran</option>
      <option>Iraq</option>
      <option>Ireland</option>
      <option>Isle of Man</option>
      <option>Israel</option>
      <option>Italy</option>
      <option>Jamaica</option>
      <option>Japan</option>
      <option>Jordan</option>
      <option>Kazakhstan</option>
      <option>Kenya</option>
      <option>Kiribati</option>
      <option>Korea North</option>
      <option>Korea South</option>
      <option>Kuwait</option>
      <option>Kyrgyzstan</option>
      <option>Laos</option>
      <option>Latvia</option>
      <option>Lebanon</option>
      <option>Lesotho</option>
      <option>Liberia</option>
      <option>Libya</option>
      <option>Liechtenstein</option>
      <option>Lithuania</option>
      <option>Luxembourg</option>
      <option>Macau</option>
      <option>Macedonia</option>
      <option>Madagascar</option>
      <option>Malawi</option>
      <option>Malaysia</option>
      <option>Maldives</option>
      <option>Mali</option>
      <option>Malta</option>
      <option>Marshall Islands</option>
      <option>Martinique</option>
      <option>Mauritania</option>
      <option>Mauritius</option>
      <option>Mayotte</option>
      <option>Mexico</option>
      <option>Midway Islands</option>
      <option>Moldova</option>
      <option>Monaco</option>
      <option>Mongolia</option>
      <option>Montserrat</option>
      <option>Morocco</option>
      <option>Mozambique</option>
      <option>Myanmar</option>
      <option>Nambia</option>
      <option>Nauru</option>
      <option>Nepal</option>
      <option>Netherland Antilles</option>
      <option>Netherlands</option>
      <option>Nevis</option>
      <option>New Caledonia</option>
      <option>New Zealand</option>
      <option>Nicaragua</option>
      <option>Niger</option>
      <option>Nigeria</option>
      <option>Niue</option>
      <option>Norfolk Island</option>
      <option>Norway</option>
      <option>Oman</option>
      <option>Pakistan</option>
      <option>Palau Island</option>
      <option>Palestine</option>
      <option>Panama</option>
      <option>Papua New Guinea</option>
      <option>Paraguay</option>
      <option>Peru</option>
      <option>Philippines</option>
      <option>Pitcairn Island</option>
      <option>Poland</option>
      <option>Portugal</option>
      <option>Puerto Rico</option>
      <option>Qatar</option>
      <option>Reunion</option>
      <option>Romania</option>
      <option>Russia</option>
      <option>Rwanda</option>
      <option>Saipan</option>
      <option>Samoa</option>
      <option>Samoa American</option>
      <option>San Marino</option>
      <option>Sao Tome & Principe</option>
      <option>Saudi Arabia</option>
      <option>Senegal</option>
      <option>Serbia & Montenegro</option>
      <option>Seychelles</option>
      <option>Sierra Leone</option>
      <option>Singapore</option>
      <option>Slovakia</option>
      <option>Slovenia</option>
      <option>Solomon Islands</option>
      <option>Somalia</option>
      <option>South Africa</option>
      <option>Spain</option>
      <option>Sri Lanka</option>
      <option>St Barthelemy</option>
      <option>St Eustatius</option>
      <option>St Helena</option>
      <option>St Kitts-Nevis</option>
      <option>St Lucia</option>
      <option>St Maarten</option>
      <option>St Pierre & Miquelon</option>
      <option>St Vincent & Grenadines</option>
      <option>Sudan</option>
      <option>Suriname</option>
      <option>Swaziland</option>
      <option>Sweden</option>
      <option>Switzerland</option>
      <option>Syria</option>
      <option>Tahiti</option>
      <option>Taiwan</option>
      <option>Tajikistan</option>
      <option>Tanzania</option>
      <option>Thailand</option>
      <option>Togo</option>
      <option>Tokelau</option>
      <option>Tonga</option>
      <option>Trinidad & Tobago</option>
      <option>Tunisia</option>
      <option>Turkey</option>
      <option>Turkmenistan</option>
      <option>Turks & Caicos Is</option>
      <option>Tuvalu</option>
      <option>Uganda</option>
      <option>Ukraine</option>
      <option>United Arab Emirates</option>
      <option>United Kingdom</option>
      <option>Uruguay</option>
      <option>USA</option>
      <option>Uzbekistan</option>
      <option>Vanuatu</option>
      <option>Vatican City State</option>
      <option>Venezuela</option>
      <option>Vietnam</option>
      <option>Virgin Islands (Brit)</option>
      <option>Virgin Islands (USA)</option>
      <option>Wake Island</option>
      <option>Wallis & Futana Is</option>
      <option>Yemen</option>
      <option>Zaire</option>
      <option>Zambia</option>
      <option>Zimbabwe</option>
   </select></tr>
   <tr><td align="right">Address:</td>         <td><input type="text"     name="user[address]"        value="<?=$this->user[address]?>"        size="30" /></td></tr>
   <tr><td align="right">Phone:</td>           <td><input type="text"     name="user[phone]"          value="<?=$this->user[phone]?>"          size="30" /></td></tr>
   <tr><td align="right">Phone password:</td>  <td><input type="text"     name="user[phone_password]" value="<?=$this->user[phone_password]?>" size="30" /></td></tr>
   <tr><td align="right">Send reports:</td>    <td><input type="checkbox" name="user[send_reports]"   value="1" checked/>                                  </td></tr>
   <tr><td align="right" nowrap>Verification code:</td><td><img src="wr_image.php" width="60" height="22" align="absbottom" style="border: 1px dashed buttonshadow;"/>&nbsp;&nbsp;confirm: <input type="text" name="verify_code" size="6" style="width: 55px;"/></td>
   </tr>
   <tr><td>&nbsp;</td>                         <td><input type="submit" name="a[register]" value="Register" size="30" style="width: 175px;"/></td></tr>
</form>
</div>
</html>