//+------------------------------------------------------------------+
//|                                                        UniFeeder |
//|                 Copyright © 2001-2008, MetaQuotes Software Corp. |
//|                                         http://www.metaquotes.ru |
//+------------------------------------------------------------------+
//|                                                                  |
//|                    DO NOT EDIT THIS FILE!                        |
//|            IT MAY CAUSE ERRORS IN WORK OF A SERVER               |
//+------------------------------------------------------------------+
#pragma once
//+------------------------------------------------------------------+
//| Feeder work mode                                                 |
//+------------------------------------------------------------------+
enum FeederModes
  {
   modeOnlyQuotes    =0,                         // feeder can take quotes only
   modeOnlyNews      =1,                         // feeder can take news only
   modeQuotesAndNews =2,                         // feeder can take quotes and news as well
   modeQuotesOrNews  =3                          // feeder can take quotes or news only
  };
//+------------------------------------------------------------------+
//| Feeder description                                               |
//+------------------------------------------------------------------+
struct FeedDescription
  {
   int               version;                    // feeder version
   char              name[128];                  // feeder name
   char              copyright[128];             // copyright string
   char              web[128];                   // web information
   char              email[128];                 // e-mail
   char              server[128];                // communicating server
   char              username[32];               // default login
   char              userpass[32];               // default password
   int               modes;                      // mode (see FeederModes enum)
   char              description[512];           // feeder short description
   int               reserved[62];               // reserverd/unused
  };
//+------------------------------------------------------------------+
//| The data for transfer to a server (quotes and news)              |
//+------------------------------------------------------------------+
#pragma pack(push,1)
struct FeedTick
  {
   char              symbol[16];                 // инструмент
   time_t            ctm;                        // время
   char              bank[32];                   // банк(источник)
   double            bid,ask;                    // котировки
   char              reserved[12];               // резерв/выравнивание
  };
struct FeedData
  {
   //---- данные котировок
   FeedTick          ticks[32];
   int               ticks_count;                // число пришедших котировок
   //---- данные новостей
   char              news_time[32];              // время поступления
   char              subject[256];               // заголовок (тема)
   char              category[64];               // категория
   char              keywords[256];              // ключевые слова
   char             *body;                       // тело новости
   int               body_len;                   // длина тела новости
   int               body_maxlen;                // макс. размер тела новости
   //---- результаты операций
   int               result;                     // результат работы
   char              result_string[256];         // описание ошибки
   int               feeder;                     // индекс фидера(для внутреннего исп-я)
   int               mode;                       // режим-0-котировка, 1 -новость, 2-новость и котировка
   //----
   char              reserved[68];               // резерв
  };
#pragma pack(pop)
//+------------------------------------------------------------------+
//| Virtual interface                                                |
//+------------------------------------------------------------------+
class CFeedInterface
  {
public:
   //---- virtual methods
   virtual int       Connect(LPCSTR server,LPCSTR login,LPCSTR password)=0;
   virtual void      Close(void)                    =0;
   virtual void      SetSymbols(LPCSTR symbols)     =0;
   virtual int       Read(FeedData *data)           =0;
   virtual int       Journal(char *buffer)          =0;
   //----
  };
//+------------------------------------------------------------------+
